spring:
  datasource:
    username: root
    password: 19031903Au
    url: jdbc:mysql://localhost:3306/utilityBills
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    root: warn
    '[com.project]': debug
    spring:
 